name: TestDriver.ai / Generate / Explore

permissions:
  actions: read
  contents: write
  pull-requests: write

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: 1. /generate
          prerun: |
            cd $env:TEMP
            npm init -y
            npm install dashcam-chrome
            Start-Process "C:/Program Files/Google/Chrome/Application/chrome.exe" -ArgumentList "--start-maximized", "--load-extension=$(pwd)/node_modules/dashcam-chrome/build", "${{ vars.TESTDRIVER_WEBSITE }}"
            exit        
          pr-title: "TestDriver.ai / Generate Test Plans"
          pr-branch: testdriver/generate-${{ github.run_id }}-${{ github.run_attempt }}
        env:
          FORCE_COLOR: "3"
